UI complete
IMR4Power/Game pull request #7
Opened 2020-06-27 15:30 UTC by DoBrcd

2020-06-27 20:30 UTC, Enoriz commented on src/model/Columns.java
> +    public int getHauteur() {
in english please

2020-06-27 20:30 UTC, Enoriz commented on src/model/Columns.java
> +    public void Empile(Checker checker) {
in english please

2020-06-27 20:31 UTC, Enoriz commented on src/model/Game.java
> +    private boolean jouerPion(Joueur j, int colonneIndex) {
in english please

2020-06-27 20:31 UTC, Enoriz commented on src/model/Game.java
> +    public boolean JouerPion(int colonneIndex) {
in english please

2020-06-27 20:32 UTC, Enoriz commented on src/model/GameBoard.java
> +    public boolean JouerPion(Joueur joueur, int colonneIndex) {
in english please

2020-06-27 20:32 UTC, Enoriz commented on src/model/Joueur.java
> +    public Joueur (String name ,Color color){
in english please

2020-06-30 03:43 UTC, zartech22 requested changes
Petites modifications

2020-06-30 03:43 UTC, zartech22 commented on src/application/GameBoard.java
> +    private void createBoard(int row, int columns) {
row -> rows

2020-06-30 03:43 UTC, zartech22 commented on src/application/GameBoard.java
> +    private void clicOnColums(VBox vBox) {
clickOnColumn

2020-06-30 03:43 UTC, zartech22 commented on src/application/MainFrame.java
> +            loader.setLocation(Main.class.getResource("../FXML/GameBoard.fxml"));
use this.class()

2020-06-30 03:43 UTC, zartech22 commented on src/application/MainFrame.java
> +            BoardParameters params = new BoardParameters(row, columns);
row -> rows

2020-06-30 03:43 UTC, zartech22 commented on src/application/NewGameDialog.java
> +        btnJouer.setOnMouseClicked(e -> MainFrame.getMainFrame().startGame(parameters));
In english

2020-06-30 03:43 UTC, zartech22 commented on src/application/WelcomeStage.java
>      private Button nouvellePartie, afficherScores, quitter;
In english

2020-06-30 03:43 UTC, zartech22 commented on src/model/BoardParameters.java
> +        this.nbRow = new SimpleIntegerProperty(row);
Row -> Rows

2020-06-30 03:43 UTC, zartech22 commented on src/model/Game.java
>      private int actualPlayer, nbPlayer;
actualPlayer -> currentPlayer

2020-06-30 03:56 UTC, zartech22 approved these changes

2020-06-30 03:56 UTC, merged